/**
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.14.3/userguide/multi_project_builds.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */
pluginManagement {
  includeBuild("../")

  plugins {
    id("dev.fnc314.gradle.plugins.settings.project-collections-gradle-settings-plugin") version ("5.0.3")
  }

}

plugins {
  id("dev.fnc314.gradle.plugins.settings.project-collections-gradle-settings-plugin") version ("5.0.3")
}

projectCollections {
  listOf(
    "components",
    "design-system",
  ).onEach { it toDepthOf 1 }

  "features" toDepthOf 3

  fileSpec.set { it.name.first().toString() !in listOf("_", ".", "-") }
  projectNameTransform.set { projectPath ->
    projectPath.replace(oldValue = ":", newValue = "-")
      .removePrefix("-")
      .also { println("$projectPath Replaced With $it") }
  }
}

rootProject.name = "project-collections-gradle-settings-plugin-sample"