concurrency:
  cancel-in-progress: true
  group: "pages"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: "26"

      - name: Gradle Setup
        uses: gradle/actions/setup-gradle@v6
        with:
          gradle-version: wrapper
          add-job-summary-as-pr-comment: always

      - name: Gradle Build
        run: "./gradlew plugin:assemble"
  docs:
    runs-on: ubuntu-latest
    steps:

  publish:
    runs-on: ubuntu-latest
    steps:

name: Publish Dokka and Kdoc/Javadoc Artifacts

on:
  push:
    branches: [
      "main"
    ]

  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  pages: write