concurrency:
  cancel-in-progress: false
  group: "pages"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Generate Dokka documentation
        run: ./gradlew dokkaHtml

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs/dokka'

      - id: deployment
        name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4

name: Publish Dokka Docs to GitHub Pages

on:
  push:
    tags:
      - 'version/[0-9]+.[0-9]+.[0-9]+*'

permissions:
  contents: read
  id-token: write
  pages: write
